Graph plotting
PyRigi/PyRigi pull request #73
Opened 2024-07-31 17:41 UTC by Legersky

I have polished a bit the plotting functionality implemented by @lenkakusnirova.
Thanks to her, graphs can be plotted now with various formatting options.
The same options are available for plotting planar frameworks.

We should decide for better default colors (@ggmath ?) and whether we want to distinguish plots of graphs and frameworks somehow.

If we do not mind adding a dependency, we could use this package to have automatically generated colors that are more distinct for the option `edge_color` when a partition of edges is specified: https://distinctipy.readthedocs.io/en/latest/

2024-08-06 14:17 UTC, MatteoGallet commented
Thanks to @lenkakusnirova!

It seems to me that `distinctipy` seems a nice and light tool, I would be in favor of using it.

One aspect that we may change: the `doc_category` of the `plot` method in `Graph` is `"Other"`, while the `doc_category` of the `plot` method in `Framework` is `"Plotting"`.

2024-08-07 10:55 UTC, MatteoGallet requested changes

2024-08-07 10:55 UTC, MatteoGallet commented on pyrigi/graph.py
> +                            "Input includes edge that is not part of the framework"
"Input includes edge" -> "The input includes an edge"

2024-08-07 10:55 UTC, MatteoGallet commented on pyrigi/graph.py
> +            )
Shall we provide a more refined error message, i.e, identify which edge(s) color is specified multiple times?

2024-08-07 10:55 UTC, MatteoGallet commented on pyrigi/graph.py
> +        This method a is wrapper for functions
"This method a is wrapper for functions" -> "This method a is wrapper for the functions"

2024-08-07 10:55 UTC, MatteoGallet commented on pyrigi/graph.py
> +            then it is generated using :meth:`~Graph.layout`.
What does "it" refer to here?

2024-08-07 10:55 UTC, MatteoGallet commented on pyrigi/graph.py
> +            The color of the vertices. Color can be string or rgb (or rgba)
"Color can be" -> "The color can be"

2024-08-07 10:55 UTC, MatteoGallet commented on pyrigi/graph.py
> +            If a (possible incomplete) partition of the edges is given,
"possible incomplete" -> "possibly incomplete"

2024-08-07 10:55 UTC, MatteoGallet commented on pyrigi/graph.py
> +            If a dictionary from color to a list of edge is given,
"from color to a list" -> "from colors to a list"

2024-08-07 11:19 UTC, Legersky commented on pyrigi/graph.py
> +            )
As you prefer, I was lazy to implement something robust enough to deal with swapped vertices when specified second time.

2024-08-07 11:20 UTC, Legersky commented on pyrigi/graph.py
> +            then it is generated using :meth:`~Graph.layout`.
placement

2024-08-07 11:21 UTC, MatteoGallet commented on pyrigi/graph.py
> +            then it is generated using :meth:`~Graph.layout`.
Ok! But why is this in the specification of the "layout" parameter?

2024-08-07 11:22 UTC, MatteoGallet commented on pyrigi/graph.py
> +            )
Ok,  I will try something, if it becomes too complicated, I will leave it as it is.

2024-08-07 11:30 UTC, Legersky commented on pyrigi/graph.py
> +            then it is generated using :meth:`~Graph.layout`.
Sorry for the confusing description: one can specify directly a `placement` (dict from vertices to points). If this parameter is omitted, the method generates a placement using method `layout` and in this parameter, one can specify which layout should be used (`spring`, `circular`, `random` or `planar`).

2024-08-07 15:33 UTC, MatteoGallet approved these changes

2024-08-07 15:57 UTC, MatteoGallet approved these changes

2024-08-07 15:57 UTC, merged