Feature pebble game algorithm
PyRigi/PyRigi pull request #82
Opened 2024-08-27 08:59 UTC by mihalykoandras

This adds all features to support the pebble game algorithm that is necessary for the 2d combinatorial rigidity. 

I added a new class directed_graph, that supports the directed graph structure necessary for the pebble game algorithm. I connected the relevant functions of Graph to the directed_graph class. 
Some unit tests are added for both classes.

This is not necessarily a complete implementation of every potential of the pebble game algorithm, but a first - simple - approach for it, that can be improved later down the line. I'm not even 100% sure on the O(|V|^2) nature of this implementation, since that depends on the internal implementations of python. 
But I believe that this is a usable implementation that can be a good basis of further development.

2024-08-27 10:58 UTC, MatteoGallet commented
Thanks a lot @mihalykoandras !! I took the liberty to make a couple of minimal changes to that the code would pass the `flake8` check. Is it ok to comment out the two `print` statements in the `is_rigid` method of `Graph` so that the tests will not fail?

2024-08-27 11:59 UTC, mihalykoandras commented
Thanks for the flake fix. I removed the unnecessary print() statements.

2024-08-27 11:59 UTC, MatteoGallet commented
> Thanks for the flake fix. I removed the unnecessary print() statements.

Thanks a lot!

2024-08-27 12:03 UTC, MatteoGallet commented
Would it be ok to transform the comments to the methods at the end of `directed_graph.py` into docstrings? I can take care of that if you agree.

2024-08-29 18:38 UTC, mihalykoandras commented
I updated the docstrings. While I believe there are still some unit tests that I'd need to add, I will move it to ready state from draft.

2024-09-23 09:51 UTC, MatteoGallet requested changes
Requested changes for PEP 257 compliance.

2024-09-23 09:51 UTC, MatteoGallet commented on pyrigi/directed_graph.py
> +        Checks if edge can be added between the vertices u and v
"Checks" -> "Check"

2024-09-23 09:51 UTC, MatteoGallet commented on pyrigi/directed_graph.py
> +        It returns if the given edge can be added
"It returns if" -> "Return whether"

2024-09-23 09:51 UTC, MatteoGallet commented on pyrigi/directed_graph.py
> +            Running depth first search to find vertices
"Running" -> "Run"

2024-09-23 09:51 UTC, MatteoGallet commented on pyrigi/directed_graph.py
> +            Returns if any of these has outdegree < self._K
"Returns if" -> "Return whether"

2024-09-23 09:51 UTC, MatteoGallet commented on pyrigi/directed_graph.py
> +        Can you add the edge between the nodes u and v,
"Can you add" -> "Check whether one can add"

2024-09-23 09:51 UTC, MatteoGallet commented on pyrigi/directed_graph.py
> +        Function to add the given edge to the directed graph, if possible.
"Function to add" -> "Add"

2024-09-23 09:51 UTC, MatteoGallet commented on pyrigi/directed_graph.py
> +        Simple way to add a list of edges to the directed graph
"Simple way to add" -> "Add"

2024-09-23 09:51 UTC, MatteoGallet commented on pyrigi/graph.py
> +        Builds and saves the directed representation of the graph from scratch.
"Builds and saves" -> "Build and save"

2024-09-23 09:51 UTC, MatteoGallet commented on pyrigi/graph.py
> +        :prf:ref:`(K, L)-independent <def-kl-sparse-tight>` from the graph?
"Is the (not yet existing) edge between u and v would be :prf:ref:`(K, L)-independent <def-kl-sparse-tight>` from the graph?" -> "Check whether the (not yet existing) edge between u and v would be :prf:ref:`(K, L)-independent <def-kl-sparse-tight>` from the graph."

2024-09-23 09:51 UTC, MatteoGallet commented on pyrigi/graph.py
> +        from the graph, it is uv.
"What is the fundamental circuit of the (not yet existing) edge between u and v? If uv is :prf:ref:`(K, L)-independent <def-kl-sparse-tight>` from the graph, it is uv." -> "Return the fundamental circuit of the (not yet existing) edge between u and v." I would put the other sentence in the Notes

2024-09-23 09:51 UTC, MatteoGallet commented on pyrigi/graph.py
> +        Checks if the given directed graph contains exactly the same number of edges
"Checks" -> "Check"

2024-09-24 10:47 UTC, Legersky reviewed
I have added some comments regarding style and names, I will have a look at the algorithm and tests soon.

2024-09-24 10:47 UTC, Legersky commented on pyrigi/directed_graph.py
> +class MultiDiGraph(nx.MultiDiGraph):
I think we should use a different name than `MultiDiGraph` since this class is really specific for pebble games as one has to specify K and L. Namely, this is not a class that a user would use for representing a directed multigraph for some other reason than running pebble games. Actually, should this class be exposed to users at all?

2024-09-24 10:47 UTC, Legersky commented on pyrigi/directed_graph.py
> +    def in_degree(self, node: Vertex) -> int:
Is there a reason for overriding the parent method?

2024-09-24 10:47 UTC, Legersky commented on pyrigi/directed_graph.py
Docstrings of public methods should be formatted according: https://pyrigi.github.io/PyRigi/development/howto.html#docstrings
There has to be an empty line between sections, e.g. above Parameters, to be correctly compiled by Sphinx .

2024-09-24 10:47 UTC, Legersky commented on pyrigi/graph.py
> +    __directed_pebble_graph__ = pyrigi.directed_graph.MultiDiGraph()
Should this be moved to `__init__`? Moreover, it should not be a dunder name, just `_directed_pebble_graph`.

2024-09-24 10:47 UTC, Legersky commented on pyrigi/graph.py
> +    def is_independent(
I think the name is too general. (Also `get_matroid_circuit`)

2024-09-24 10:47 UTC, Legersky commented on pyrigi/graph.py
> +    def get_one_spanning_sparse_subgraph(
-> `spanning_sparse_subgraph` ?
Could you add a docstring?

2024-09-24 10:47 UTC, Legersky commented on pyrigi/graph.py
> +    def is_sparse(self, K: int, L: int, combinatorial: bool = True) -> bool:
I suggest to switch from `combinatorial` to `algorithm` which would take `"pebble"` or `"subgraph"`. That is more descriptive since both approaches are in some sense combinatorial. (We would like to adopt this also in other parts of the code where we use `combinatorial` now)

2024-09-24 10:47 UTC, Legersky commented on pyrigi/graph.py
> +        else:
This should be a fallback option also in the case when pebble games cannot be used because of the restrictions on K and L.

2024-09-28 14:54 UTC, mihalykoandras commented on pyrigi/directed_graph.py
> +        Checks if edge can be added between the vertices u and v
Ok

2024-09-28 14:55 UTC, mihalykoandras commented on pyrigi/directed_graph.py
> +        It returns if the given edge can be added
Ok

2024-09-28 14:55 UTC, mihalykoandras commented on pyrigi/directed_graph.py
> +            Running depth first search to find vertices
Ok

2024-09-28 14:55 UTC, mihalykoandras commented on pyrigi/directed_graph.py
> +            Returns if any of these has outdegree < self._K
Np

2024-09-28 14:57 UTC, mihalykoandras commented on pyrigi/graph.py
> +        Builds and saves the directed representation of the graph from scratch.
Ok

2024-09-28 14:59 UTC, mihalykoandras commented on pyrigi/graph.py
> +        :prf:ref:`(K, L)-independent <def-kl-sparse-tight>` from the graph?
Changed

2024-09-28 15:00 UTC, mihalykoandras commented on pyrigi/graph.py
> +        from the graph, it is uv.
I changed the description. What is the Notes?

2024-09-28 15:02 UTC, mihalykoandras commented on pyrigi/directed_graph.py
> +    def __check_K_and_L(self, K: int, L: int) -> None:
No, it was just a mistake.

2024-09-28 15:04 UTC, mihalykoandras commented on pyrigi/directed_graph.py
> +    def set_K(self, K: int) -> None:
Like this? I'm not that confident with python syntax as you can see.

2024-09-28 15:07 UTC, mihalykoandras commented on pyrigi/directed_graph.py
> +class MultiDiGraph(nx.MultiDiGraph):
We can rename it, as you wish. What do you suggest? PebbleGraphDirectedGraph?
Probably for the average user it is not necessary to expose this class. I remember to have asked it at the discussion and we decided that for the beginning it can be exposed, and we hide it if needed. How should I hide it?

2024-09-28 15:09 UTC, mihalykoandras commented on pyrigi/directed_graph.py
> +    def in_degree(self, node: Vertex) -> int:
Yes. In case we change to hypergraphs, this parent method won't be available any more and I wanted to introduce the framework by than. I would keep it, but I can also remove it, if you prefered like that.

2024-09-28 15:37 UTC, mihalykoandras commented on pyrigi/directed_graph.py
I changed some, hopefully it is better now. I might have still missed some though

2024-09-28 15:40 UTC, mihalykoandras commented on pyrigi/graph.py
> +    __directed_pebble_graph__ = pyrigi.directed_graph.MultiDiGraph()
Is there an __init__ though where I can put it? I don't really think that I should be the one creating the init for graph class.

2024-09-28 15:41 UTC, mihalykoandras commented on pyrigi/graph.py
> +    def is_independent(
What would you suggest instead? For this one and for the get_matroid_circuit?

2024-09-28 15:43 UTC, mihalykoandras commented on pyrigi/graph.py
> +    def get_one_spanning_sparse_subgraph(
I wouldn't change it to spanning_sparse_subgraph, if that is what you suggest. Because there are many different spanning sparse subgraphs of a graph (even maximal ones, like the one present here). So I would like to denote that this returns only one of the possible ones. 

I added the docstrings

2024-09-28 15:50 UTC, mihalykoandras commented on pyrigi/graph.py
> +    def is_sparse(self, K: int, L: int, combinatorial: bool = True) -> bool:
Sure thing. With the fallback option being "pebble" ?

2024-09-28 16:03 UTC, mihalykoandras commented on pyrigi/graph.py
> +    def is_sparse(self, K: int, L: int, combinatorial: bool = True) -> bool:
I ended up raising an error in case it is different from "pebble" and "subgraph". I hope it works

2024-09-28 16:18 UTC, mihalykoandras commented on pyrigi/graph.py
> +        else:
Ok, I did that. For that I introduced a new K,L check method, too.

2024-09-28 17:45 UTC, MatteoGallet commented on pyrigi/graph.py
> +        from the graph, it is uv.
Thanks! The Notes are an item in the docstring (as, for example, Parameters) whose content should relate to implementation details. In this sense, I believe that the sentence  If uv is `:prf:ref:(K, L)-independent <def-kl-sparse-tight>` from the graph, it is uv." would fit better into that section.

2024-09-28 18:55 UTC, MatteoGallet requested changes

2024-09-28 18:55 UTC, MatteoGallet commented on pyrigi/graph.py
>           * dim>=1: Compute the rank of the rigidity matrix and compare with edge count
Please add a blank line before TODO

2024-09-28 18:55 UTC, MatteoGallet commented on pyrigi/graph.py
> +         TODO
Please change 

```
TODO
```

into 

```
TODO
----
```

2024-09-28 18:55 UTC, MatteoGallet commented on pyrigi/graph.py
> +         TODO
Please change 

```
TODO
```

into 

```
TODO
----
```

2024-09-28 18:55 UTC, MatteoGallet commented on pyrigi/graph.py
> +         TODO
Please change 

```
TODO
```

into 

```
TODO
----
```

2024-09-30 12:16 UTC, Legersky commented on pyrigi/graph.py
> +    def is_independent(
To me, the name sounds like whether the graph is independent, while it is about a (non-)edge. Also it is not clear in what matroid. People might confuse it with the existing `Graph.is_Rd_independent`. 
What about `edge_is_kl_independent`? @MatteoGallet ?
We should also add this notion to the definition `def-kl-sparse-tight`.

2024-09-30 12:16 UTC, Legersky commented on pyrigi/graph.py
> +    def get_one_spanning_sparse_subgraph(
For me,  `spanning_sparse_subgraph` indicates clearly enough what is returned. The fact that it is not unique is immediate from the docstring, see https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.tree.mst.minimum_spanning_tree.html for comparison.

2024-09-30 17:02 UTC, mihalykoandras commented on pyrigi/graph.py
> +         TODO
Ok

2024-09-30 17:03 UTC, mihalykoandras commented on pyrigi/graph.py
> +         TODO
Ok

2024-09-30 17:05 UTC, MatteoGallet approved these changes

2024-09-30 17:16 UTC, MatteoGallet commented on pyrigi/graph.py
> +    def is_independent(
I agree with the proposed version `edge_is_kl_independent` !

2024-09-30 17:17 UTC, mihalykoandras commented on pyrigi/graph.py
> +        from the graph, it is uv.
Added

2024-09-30 17:19 UTC, mihalykoandras commented on pyrigi/directed_graph.py
> +    def in_degree(self, node: Vertex) -> int:
Sure, renamed

2024-09-30 17:22 UTC, MatteoGallet commented on pyrigi/directed_graph.py
> +class MultiDiGraph(nx.MultiDiGraph):
I agree about renaming the class, I think that for example both `PebbleDirectedGraph` and `PebbleDiGraph` would be fine! I think that we may hide this class.

2024-09-30 17:32 UTC, mihalykoandras commented on pyrigi/graph.py
> +        else:
I'm waiting for your conclusion and change accordingly.

2024-09-30 17:36 UTC, mihalykoandras commented on pyrigi/directed_graph.py
> +    def set_K(self, K: int) -> None:
Sorry, I'm not sure I understand it now. Do you prefer me keeping it like this (after the changes) or do you want me to change to @property?

2024-09-30 17:38 UTC, mihalykoandras commented on pyrigi/graph.py
> +    def is_independent(
Renamed to `edge_is_kl_independent`

2024-09-30 17:41 UTC, mihalykoandras commented on pyrigi/graph.py
> +    def get_one_spanning_sparse_subgraph(
Ok, changed.

2024-09-30 17:48 UTC, mihalykoandras commented on pyrigi/directed_graph.py
> +class MultiDiGraph(nx.MultiDiGraph):
Ok, I changed it to PebbleDiGraph and _pebble_di_graph.py .

2024-10-01 07:29 UTC, Legersky commented on pyrigi/directed_graph.py
> +    def set_K(self, K: int) -> None:
I meant that `_L` is definitely better than `__L`.
Changing to properties to avoid setters and getters would be nice as well but we can refactor it later if you don't want to bother with it now.

2024-10-01 07:30 UTC, Legersky commented on pyrigi/directed_graph.py
> +class MultiDiGraph(nx.MultiDiGraph):
`_pebble_di_graph.py` or `_pebble_digraph.py`?

2024-10-01 08:10 UTC, Legersky commented on pyrigi/graph.py
> +    __directed_pebble_graph__ = pyrigi.directed_graph.MultiDiGraph()
I see, I did not realize that we did not create `__init__` yet as it had not been needed. It really has to go to `__init__`, otherwise it is a class attribute (i.e. shared among all instances of the class), not an instance attribute.
I would say you can create one, something like:
```py
def __init__(self, graph_data=None, **attr):
    super().__init__(incoming_graph_data=graph_data, **attr)
```

2024-10-01 08:19 UTC, Legersky commented on pyrigi/graph.py
> +    def is_independent(
`get_matroid_circuit` to `edge_kl_circuit`?

2024-10-01 08:38 UTC, Legersky commented on pyrigi/graph.py
> +    __directed_pebble_graph__ = pyrigi.directed_graph.MultiDiGraph()
Actually, all tests pass even with `_directed_pebble_graph = pyrigi._pebble_di_graph.PebbleDiGraph()` deleted. I think it is because `_build_directed_graph_from_scratch` creates it anyway.

2024-10-01 13:53 UTC, MatteoGallet commented on pyrigi/framework.py
> +    def edge_is_kl_independent(self) -> bool:
Please revert this change, I believe the method `is_independent` was changed inadvertently.

2024-10-07 09:34 UTC, ggmath commented on pyrigi/graph.py
> +        else:
I am fine with a "default" parameter for algorithm .

2024-10-09 20:16 UTC, mihalykoandras commented on pyrigi/graph.py
> +    __directed_pebble_graph__ = pyrigi.directed_graph.MultiDiGraph()
I'm not 100% sure now, if I can delete it. I want to save the variable for out of the scope, too. Will it be able to reuse it if I remove the `_directed_pebble_graph = pyrigi._pebble_di_graph.PebbleDiGraph() `

2024-10-09 20:17 UTC, mihalykoandras commented on pyrigi/graph.py
> +    def is_independent(
Done

2024-10-09 20:19 UTC, mihalykoandras commented on pyrigi/framework.py
> +    def edge_is_kl_independent(self) -> bool:
Correct, thanks.

2024-10-09 20:23 UTC, mihalykoandras commented on pyrigi/graph.py
> +        else:
Let it be the 'default' path then.

2024-10-10 07:42 UTC, Legersky commented on pyrigi/graph.py
> +    __directed_pebble_graph__ = pyrigi.directed_graph.MultiDiGraph()
Yes, I think so.

2024-10-10 19:24 UTC, mihalykoandras commented on pyrigi/graph.py
> +    __directed_pebble_graph__ = pyrigi.directed_graph.MultiDiGraph()
Sure, removed it.

2024-10-10 19:43 UTC, mihalykoandras commented on pyrigi/directed_graph.py
> +    def set_K(self, K: int) -> None:
I changed it to properties. This is the very first time I use properties, so I might not get the idea at all. So please check this, if this is what you expected. I put it to the very end so that it can be reversed easily.

2024-10-11 09:51 UTC, Legersky commented on pyrigi/directed_graph.py
> +    def set_K(self, K: int) -> None:
I looks good, thanks.

2024-10-11 13:17 UTC, Legersky commented on test/test_pebble_di_graph.py
> +def test_redirect_edge():
Should this be part of `test_point_edge_head_to` instead?

2024-10-11 13:19 UTC, Legersky commented on test/test_pebble_di_graph.py
> +    assert (1, 2) in graph.edges
`(1,0)` instead?

2024-10-11 15:04 UTC, MatteoGallet commented on pyrigi/graph.py
> +        )
In order to be a bit more informative, this could be something like:

```
        raise ValueError(
            f'If specified, the value of the algorithm parameter must be one of 
            "pebble", "subgraph", or "default". Insted, it is {algorithm}.'
        )
```

2024-10-15 17:14 UTC, mihalykoandras commented on pyrigi/graph.py
> +    """
Done

2024-10-15 17:17 UTC, mihalykoandras commented on pyrigi/graph.py
> +    def edge_is_kl_independent(
I'm not familiar of how to do that. Would you please add it to the definitions?

2024-10-15 17:23 UTC, mihalykoandras commented on pyrigi/graph.py
> +        if (
Yes, I believe that is caused by removing the `    _directed_pebble_graph = pyrigi._pebble_di_graph.PebbleDiGraph()
` line. With that it should work. But yes, I'll place a warning.

2024-10-15 17:33 UTC, mihalykoandras commented on pyrigi/graph.py
> +        if (
Also, I see that the current `is_Rd_circuit` might also need a similar parameter

2024-10-15 17:34 UTC, mihalykoandras commented on pyrigi/graph.py
> +        Return the fundamental circuit of the (not yet existing) edge between u and v.
Again, I'm not familiar with the working of the definitions. If you could explain what is expected, I could add those definitions. But probably it is easier if you add them.

2024-10-15 17:36 UTC, mihalykoandras commented on pyrigi/graph.py
> +            If not specified, it defaults to "pebble".
Updated.

2024-10-15 17:38 UTC, mihalykoandras commented on pyrigi/graph.py
>          r"""
Sure, I changed them

2024-10-15 17:39 UTC, mihalykoandras commented on pyrigi/graph.py
> +                K=2, L=3, use_precomputed_directed_graph=True
Yes, I updated. There might be a need for `use_precomputed_directed_graph` option though

2024-10-15 17:40 UTC, mihalykoandras commented on pyrigi/matroid.py
True, sorry for that. Removed

2024-10-15 17:43 UTC, mihalykoandras commented on test/test_matroid.py
> +    assert M.edge_is_kl_independent([0, 2])
Done

2024-10-15 17:46 UTC, mihalykoandras commented on test/test_pebble_di_graph.py
> +def test_redirect_edge():
Correct, this is a remainder of an earlier design.

2024-10-15 18:00 UTC, mihalykoandras commented on test/test_pebble_di_graph.py
> +    assert (1, 2) in graph.edges
In fact the problem ran much deeper. We should not be able to redirect an edge to an external vertex. This should be a reversing function, only implemented like this, because later with hypergraphs this is the preferred way. I hopefully fixed it now.

2024-10-15 18:04 UTC, mihalykoandras commented on pyrigi/graph.py
> +        )
Changed so.

2024-10-15 20:27 UTC, MatteoGallet commented on pyrigi/graph.py
> +    def edge_is_kl_independent(
Sure, I can take care of that. Could you please point me to the precise mathematical definition that you implemented in the algorithm? Thanks!

2024-10-15 20:28 UTC, MatteoGallet commented on pyrigi/graph.py
> +        Return the fundamental circuit of the (not yet existing) edge between u and v.
Sure, I can take care of that as well. Could you please point me to the precise mathematical definition that you implemented in the algorithm? Thanks!

2024-10-17 18:36 UTC, mihalykoandras commented on pyrigi/graph.py
> +    def edge_is_kl_independent(
https://arxiv.org/pdf/2209.06204 p2

2024-10-17 18:37 UTC, mihalykoandras commented on pyrigi/graph.py
> +        Return the fundamental circuit of the (not yet existing) edge between u and v.
https://egres.elte.hu/tr/egres-14-12.pdf
3.5 Section, p51. It is a bit convoluted.

2024-10-17 18:39 UTC, mihalykoandras commented on pyrigi/graph.py
> +        Return the fundamental circuit of the (not yet existing) edge between u and v.
What is a circle in the (1,1)-count matroid (graphical matroid)

2024-10-17 18:40 UTC, MatteoGallet commented on pyrigi/graph.py
> +        Return the fundamental circuit of the (not yet existing) edge between u and v.
Thanks!

2024-10-17 18:40 UTC, MatteoGallet commented on pyrigi/graph.py
> +    def edge_is_kl_independent(
Thanks!

2024-10-20 16:54 UTC, mihalykoandras commented on pyrigi/directed_graph.py
> +class MultiDiGraph(nx.MultiDiGraph):
Can you confirm that this naming is acceptable?

2024-10-22 06:52 UTC, Legersky commented on pyrigi/graph.py
> +                K=2, L=3, use_precomputed_directed_graph=True
yes, I agree.

2024-10-22 15:12 UTC, MatteoGallet commented on pyrigi/directed_graph.py
> +class MultiDiGraph(nx.MultiDiGraph):
Hi! sorry for the delay! I would say that `_pebble_digraph` may be slightly better than `_pebble_di_graph` since the word "digraph" is attested, for example in [Wikipedia](https://en.wikipedia.org/wiki/Directed_graph).

2024-10-31 11:30 UTC, Legersky commented on pyrigi/_pebble_di_graph.py
> +                + " is not present in graph."
Could you replace this (and also below) by
```
f"Vertex {u} is not present in the graph."
```

2024-10-31 13:22 UTC, Legersky commented on pyrigi/_pebble_di_graph.py
> +    def redirect_edge_to_head(self, edge: Edge, node_to: Vertex) -> None:
I have fixed `Edge` and created `DirectedEdge`, see #95.

2024-11-02 21:26 UTC, mihalykoandras commented on pyrigi/_pebble_di_graph.py
> +    def redirect_edge_to_head(self, edge: Edge, node_to: Vertex) -> None:
Yes, this is preparation for the hypergraph solution, when reversing an edge doesn't make any sense, but claiming a point to be the head now makes sense. It might be a bit confusing now, but I would keep it unless you insist on the change.

2024-11-02 21:28 UTC, MatteoGallet commented on pyrigi/_pebble_di_graph.py
> +    def redirect_edge_to_head(self, edge: Edge, node_to: Vertex) -> None:
I see, thanks for the explanation! I would say, then please leave it as it is.

2024-11-03 15:28 UTC, mihalykoandras commented on pyrigi/directed_graph.py
> +class MultiDiGraph(nx.MultiDiGraph):
Sure, done

2024-11-03 15:31 UTC, mihalykoandras commented on pyrigi/_pebble_di_graph.py
> +    def redirect_edge_to_head(self, edge: Edge, node_to: Vertex) -> None:
I'm unsure now, what do you mean by fixing? So what you suggest me to do is to use DirectedEdge in everywhere in the _pebble_digraph class?

2024-11-03 15:33 UTC, mihalykoandras commented on pyrigi/_pebble_di_graph.py
> +                + " is not present in graph."
Sure, fixed.

2024-11-03 15:35 UTC, mihalykoandras commented on pyrigi/_pebble_di_graph.py
> +            node: Vertex, visited: set, edge_path: list[Edge], current_edge=None
Fixed

2024-11-03 15:40 UTC, mihalykoandras commented on pyrigi/_pebble_di_graph.py
> +    def redirect_edge_to_head(self, edge: Edge, node_to: Vertex) -> None:
Ok, I did just that, please check if you wished like this.

2024-11-03 15:57 UTC, mihalykoandras commented on pyrigi/graph.py
> +        if (
Ok, I added  use_precomputed_pebble_digraph to hopefully all relevant places.

2024-11-03 16:10 UTC, mihalykoandras commented on pyrigi/graph.py
> +                K=2, L=3, use_precomputed_directed_graph=True
I placed use_precomputed_pebble_digraph hopefully in every relevant place now and added comments in every function, with always being the default value False.

2024-11-03 17:10 UTC, Legersky commented on pyrigi/graph.py
> +        if (
Thanks, I think so. I would just change to warning a bit: I guess it is not only about `AtributeError`, but the result might be just wrong if the graph was modified without appropriate change of the pebble digraph, cannot it?

2024-11-03 17:13 UTC, Legersky commented on pyrigi/_pebble_di_graph.py
> +    def redirect_edge_to_head(self, edge: Edge, node_to: Vertex) -> None:
Thanks, that's what I meant. Now it is clear from the signature that the order of vertices matters.

2024-11-04 21:48 UTC, mihalykoandras commented on pyrigi/graph.py
> +        if (
So what should I change it to?

2024-11-05 13:47 UTC, Legersky commented on pyrigi/graph.py
> +        if (
What about 'Use True only if you are certain that the pebble game directed graph is consistent with the graph.'?
I can change it.

2024-11-05 16:54 UTC, MatteoGallet commented on pyrigi/graph.py
> +        if (
Thanks! We'll have a look at the docstrings and then we will merge the branch if we have no further questions.

2024-11-05 21:09 UTC, Legersky approved these changes

2024-11-05 21:10 UTC, merged